version: '3'
services:
  firecares:
    build:
      context: ./
    image: firecares
    volumes:
      - ./static:/webapps/firecares/static/
    ports:
     - 8000:8000
     - 1337:1337
    env_file:
      - .env.local
    command: ['./manage.py', 'runserver', '--settings=firecares.settings.local']
