version: '3.7' 

networks:
  public:
    name: public
    external: true

services:

  firecares:
    build:
      context: ./
    image: firecares
    volumes:
      - ./:/webapps/firecares/
    ports:
     - 0.0.0.0:8000:8000
     - 1337:1337
    env_file:
      - .env.local
    networks:
      - public
    depends_on:
      - postgis

    command: ['./manage.py', 'runserver', '--settings=firecares.settings.local', '0.0.0.0:8000']

  postgis:
    image: mdillon/postgis
    env_file:
      - .env.local
    environment:
      - POSTGRES_PASSWORD=$DATABASE_PASSWORD
      - POSTGRES_DB=$DATABASE_NAME
      - POSTGRES_USER=$DATABASE_USER
    volumes:
      - "$HOME/postgresql:/var/lib/postgresql"
    networks:
      - public
    ports:
      - 0.0.0.0:$DATABASE_PORT:$DATABASE_PORT
