# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations
import django.contrib.gis.db.models.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('firestation', '0012_firedepartment_population_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopulationClass0Quartile',
            fields=[
                ('id', models.ForeignKey(primary_key=True, db_column=b'id', serialize=False, to='firestation.FireDepartment')),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField(editable=False)),
                ('fdid', models.CharField(max_length=10, editable=False)),
                ('name', models.CharField(max_length=100, editable=False)),
                ('headquarters_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, editable=False, blank=True)),
                ('headquarters_fax', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, editable=False, blank=True)),
                ('department_type', models.CharField(max_length=20, null=True, editable=False, blank=True)),
                ('organization_type', models.CharField(max_length=75, null=True, editable=False, blank=True)),
                ('website', models.URLField(null=True, editable=False, blank=True)),
                ('state', models.CharField(max_length=2, editable=False)),
                ('region', models.CharField(max_length=20, null=True, editable=False, blank=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326, null=True, editable=False, blank=True)),
                ('dist_model_score', models.FloatField(null=True, editable=False, blank=True)),
                ('risk_model_deaths', models.FloatField(verbose_name=b'Predicted deaths per year.', null=True, editable=False, blank=True)),
                ('risk_model_injuries', models.FloatField(verbose_name=b'Predicted injuries per year.', null=True, editable=False, blank=True)),
                ('risk_model_fires', models.FloatField(verbose_name=b'Predicted number of fires per year.', null=True, editable=False, blank=True)),
                ('risk_model_fires_size0', models.FloatField(verbose_name=b'Predicted number of size 0 fires.', null=True, editable=False, blank=True)),
                ('risk_model_fires_size0_percentage', models.FloatField(verbose_name=b'Percentage of size 0 fires.', null=True, editable=False, blank=True)),
                ('risk_model_fires_size1', models.FloatField(verbose_name=b'Predicted number of size 1 fires.', null=True, editable=False, blank=True)),
                ('risk_model_fires_size1_percentage', models.FloatField(verbose_name=b'Percentage of size 1 fires.', null=True, editable=False, blank=True)),
                ('risk_model_fires_size2', models.FloatField(verbose_name=b'Predicted number of size 2 firese.', null=True, editable=False, blank=True)),
                ('risk_model_fires_size2_percentage', models.FloatField(verbose_name=b'Percentage of size 2 fires.', null=True, editable=False, blank=True)),
                ('population', models.IntegerField(null=True, editable=False, blank=True)),
                ('population_class', models.IntegerField(null=True, editable=False, blank=True)),
                ('featured', models.BooleanField(default=False, editable=False)),
                ('dist_model_score_quartile', models.IntegerField()),
                ('risk_model_deaths_quartile', models.IntegerField()),
                ('risk_model_injuries_quartile', models.IntegerField()),
                ('risk_model_fires_size0_quartile', models.IntegerField()),
                ('risk_model_fires_size1_quartile', models.IntegerField()),
                ('risk_model_fires_size2_quartile', models.IntegerField()),
                ('risk_model_fires_quartile', models.IntegerField()),
                ('risk_model_fires_size1_percentage_risk_model_fires_size2_percen', models.IntegerField()),
                ('risk_model_deaths_risk_model_injuries_quartile', models.IntegerField()),
            ],
            options={
                'abstract': False,
                'db_table': 'population_class_0_quartiles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PopulationClass1Quartile',
            fields=[
                ('id', models.ForeignKey(primary_key=True, db_column=b'id', serialize=False, to='firestation.FireDepartment')),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField(editable=False)),
                ('fdid', models.CharField(max_length=10, editable=False)),
                ('name', models.CharField(max_length=100, editable=False)),
                ('headquarters_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, editable=False, blank=True)),
                ('headquarters_fax', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, editable=False, blank=True)),
                ('department_type', models.CharField(max_length=20, null=True, editable=False, blank=True)),
                ('organization_type', models.CharField(max_length=75, null=True, editable=False, blank=True)),
                ('website', models.URLField(null=True, editable=False, blank=True)),
                ('state', models.CharField(max_length=2, editable=False)),
                ('region', models.CharField(max_length=20, null=True, editable=False, blank=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326, null=True, editable=False, blank=True)),
                ('dist_model_score', models.FloatField(null=True, editable=False, blank=True)),
                ('risk_model_deaths', models.FloatField(verbose_name=b'Predicted deaths per year.', null=True, editable=False, blank=True)),
                ('risk_model_injuries', models.FloatField(verbose_name=b'Predicted injuries per year.', null=True, editable=False, blank=True)),
                ('risk_model_fires', models.FloatField(verbose_name=b'Predicted number of fires per year.', null=True, editable=False, blank=True)),
                ('risk_model_fires_size0', models.FloatField(verbose_name=b'Predicted number of size 0 fires.', null=True, editable=False, blank=True)),
                ('risk_model_fires_size0_percentage', models.FloatField(verbose_name=b'Percentage of size 0 fires.', null=True, editable=False, blank=True)),
                ('risk_model_fires_size1', models.FloatField(verbose_name=b'Predicted number of size 1 fires.', null=True, editable=False, blank=True)),
                ('risk_model_fires_size1_percentage', models.FloatField(verbose_name=b'Percentage of size 1 fires.', null=True, editable=False, blank=True)),
                ('risk_model_fires_size2', models.FloatField(verbose_name=b'Predicted number of size 2 firese.', null=True, editable=False, blank=True)),
                ('risk_model_fires_size2_percentage', models.FloatField(verbose_name=b'Percentage of size 2 fires.', null=True, editable=False, blank=True)),
                ('population', models.IntegerField(null=True, editable=False, blank=True)),
                ('population_class', models.IntegerField(null=True, editable=False, blank=True)),
                ('featured', models.BooleanField(default=False, editable=False)),
                ('dist_model_score_quartile', models.IntegerField()),
                ('risk_model_deaths_quartile', models.IntegerField()),
                ('risk_model_injuries_quartile', models.IntegerField()),
                ('risk_model_fires_size0_quartile', models.IntegerField()),
                ('risk_model_fires_size1_quartile', models.IntegerField()),
                ('risk_model_fires_size2_quartile', models.IntegerField()),
                ('risk_model_fires_quartile', models.IntegerField()),
                ('risk_model_fires_size1_percentage_risk_model_fires_size2_percen', models.IntegerField()),
                ('risk_model_deaths_risk_model_injuries_quartile', models.IntegerField()),
            ],
            options={
                'abstract': False,
                'db_table': 'population_class_1_quartiles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PopulationClass2Quartile',
            fields=[
                ('id', models.ForeignKey(primary_key=True, db_column=b'id', serialize=False, to='firestation.FireDepartment')),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField(editable=False)),
                ('fdid', models.CharField(max_length=10, editable=False)),
                ('name', models.CharField(max_length=100, editable=False)),
                ('headquarters_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, editable=False, blank=True)),
                ('headquarters_fax', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, editable=False, blank=True)),
                ('department_type', models.CharField(max_length=20, null=True, editable=False, blank=True)),
                ('organization_type', models.CharField(max_length=75, null=True, editable=False, blank=True)),
                ('website', models.URLField(null=True, editable=False, blank=True)),
                ('state', models.CharField(max_length=2, editable=False)),
                ('region', models.CharField(max_length=20, null=True, editable=False, blank=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326, null=True, editable=False, blank=True)),
                ('dist_model_score', models.FloatField(null=True, editable=False, blank=True)),
                ('risk_model_deaths', models.FloatField(verbose_name=b'Predicted deaths per year.', null=True, editable=False, blank=True)),
                ('risk_model_injuries', models.FloatField(verbose_name=b'Predicted injuries per year.', null=True, editable=False, blank=True)),
                ('risk_model_fires', models.FloatField(verbose_name=b'Predicted number of fires per year.', null=True, editable=False, blank=True)),
                ('risk_model_fires_size0', models.FloatField(verbose_name=b'Predicted number of size 0 fires.', null=True, editable=False, blank=True)),
                ('risk_model_fires_size0_percentage', models.FloatField(verbose_name=b'Percentage of size 0 fires.', null=True, editable=False, blank=True)),
                ('risk_model_fires_size1', models.FloatField(verbose_name=b'Predicted number of size 1 fires.', null=True, editable=False, blank=True)),
                ('risk_model_fires_size1_percentage', models.FloatField(verbose_name=b'Percentage of size 1 fires.', null=True, editable=False, blank=True)),
                ('risk_model_fires_size2', models.FloatField(verbose_name=b'Predicted number of size 2 firese.', null=True, editable=False, blank=True)),
                ('risk_model_fires_size2_percentage', models.FloatField(verbose_name=b'Percentage of size 2 fires.', null=True, editable=False, blank=True)),
                ('population', models.IntegerField(null=True, editable=False, blank=True)),
                ('population_class', models.IntegerField(null=True, editable=False, blank=True)),
                ('featured', models.BooleanField(default=False, editable=False)),
                ('dist_model_score_quartile', models.IntegerField()),
                ('risk_model_deaths_quartile', models.IntegerField()),
                ('risk_model_injuries_quartile', models.IntegerField()),
                ('risk_model_fires_size0_quartile', models.IntegerField()),
                ('risk_model_fires_size1_quartile', models.IntegerField()),
                ('risk_model_fires_size2_quartile', models.IntegerField()),
                ('risk_model_fires_quartile', models.IntegerField()),
                ('risk_model_fires_size1_percentage_risk_model_fires_size2_percen', models.IntegerField()),
                ('risk_model_deaths_risk_model_injuries_quartile', models.IntegerField()),
            ],
            options={
                'abstract': False,
                'db_table': 'population_class_2_quartiles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PopulationClass3Quartile',
            fields=[
                ('id', models.ForeignKey(primary_key=True, db_column=b'id', serialize=False, to='firestation.FireDepartment')),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField(editable=False)),
                ('fdid', models.CharField(max_length=10, editable=False)),
                ('name', models.CharField(max_length=100, editable=False)),
                ('headquarters_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, editable=False, blank=True)),
                ('headquarters_fax', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, editable=False, blank=True)),
                ('department_type', models.CharField(max_length=20, null=True, editable=False, blank=True)),
                ('organization_type', models.CharField(max_length=75, null=True, editable=False, blank=True)),
                ('website', models.URLField(null=True, editable=False, blank=True)),
                ('state', models.CharField(max_length=2, editable=False)),
                ('region', models.CharField(max_length=20, null=True, editable=False, blank=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326, null=True, editable=False, blank=True)),
                ('dist_model_score', models.FloatField(null=True, editable=False, blank=True)),
                ('risk_model_deaths', models.FloatField(verbose_name=b'Predicted deaths per year.', null=True, editable=False, blank=True)),
                ('risk_model_injuries', models.FloatField(verbose_name=b'Predicted injuries per year.', null=True, editable=False, blank=True)),
                ('risk_model_fires', models.FloatField(verbose_name=b'Predicted number of fires per year.', null=True, editable=False, blank=True)),
                ('risk_model_fires_size0', models.FloatField(verbose_name=b'Predicted number of size 0 fires.', null=True, editable=False, blank=True)),
                ('risk_model_fires_size0_percentage', models.FloatField(verbose_name=b'Percentage of size 0 fires.', null=True, editable=False, blank=True)),
                ('risk_model_fires_size1', models.FloatField(verbose_name=b'Predicted number of size 1 fires.', null=True, editable=False, blank=True)),
                ('risk_model_fires_size1_percentage', models.FloatField(verbose_name=b'Percentage of size 1 fires.', null=True, editable=False, blank=True)),
                ('risk_model_fires_size2', models.FloatField(verbose_name=b'Predicted number of size 2 firese.', null=True, editable=False, blank=True)),
                ('risk_model_fires_size2_percentage', models.FloatField(verbose_name=b'Percentage of size 2 fires.', null=True, editable=False, blank=True)),
                ('population', models.IntegerField(null=True, editable=False, blank=True)),
                ('population_class', models.IntegerField(null=True, editable=False, blank=True)),
                ('featured', models.BooleanField(default=False, editable=False)),
                ('dist_model_score_quartile', models.IntegerField()),
                ('risk_model_deaths_quartile', models.IntegerField()),
                ('risk_model_injuries_quartile', models.IntegerField()),
                ('risk_model_fires_size0_quartile', models.IntegerField()),
                ('risk_model_fires_size1_quartile', models.IntegerField()),
                ('risk_model_fires_size2_quartile', models.IntegerField()),
                ('risk_model_fires_quartile', models.IntegerField()),
                ('risk_model_fires_size1_percentage_risk_model_fires_size2_percen', models.IntegerField()),
                ('risk_model_deaths_risk_model_injuries_quartile', models.IntegerField()),
            ],
            options={
                'abstract': False,
                'db_table': 'population_class_3_quartiles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PopulationClass4Quartile',
            fields=[
                ('id', models.ForeignKey(primary_key=True, db_column=b'id', serialize=False, to='firestation.FireDepartment')),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField(editable=False)),
                ('fdid', models.CharField(max_length=10, editable=False)),
                ('name', models.CharField(max_length=100, editable=False)),
                ('headquarters_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, editable=False, blank=True)),
                ('headquarters_fax', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, editable=False, blank=True)),
                ('department_type', models.CharField(max_length=20, null=True, editable=False, blank=True)),
                ('organization_type', models.CharField(max_length=75, null=True, editable=False, blank=True)),
                ('website', models.URLField(null=True, editable=False, blank=True)),
                ('state', models.CharField(max_length=2, editable=False)),
                ('region', models.CharField(max_length=20, null=True, editable=False, blank=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326, null=True, editable=False, blank=True)),
                ('dist_model_score', models.FloatField(null=True, editable=False, blank=True)),
                ('risk_model_deaths', models.FloatField(verbose_name=b'Predicted deaths per year.', null=True, editable=False, blank=True)),
                ('risk_model_injuries', models.FloatField(verbose_name=b'Predicted injuries per year.', null=True, editable=False, blank=True)),
                ('risk_model_fires', models.FloatField(verbose_name=b'Predicted number of fires per year.', null=True, editable=False, blank=True)),
                ('risk_model_fires_size0', models.FloatField(verbose_name=b'Predicted number of size 0 fires.', null=True, editable=False, blank=True)),
                ('risk_model_fires_size0_percentage', models.FloatField(verbose_name=b'Percentage of size 0 fires.', null=True, editable=False, blank=True)),
                ('risk_model_fires_size1', models.FloatField(verbose_name=b'Predicted number of size 1 fires.', null=True, editable=False, blank=True)),
                ('risk_model_fires_size1_percentage', models.FloatField(verbose_name=b'Percentage of size 1 fires.', null=True, editable=False, blank=True)),
                ('risk_model_fires_size2', models.FloatField(verbose_name=b'Predicted number of size 2 firese.', null=True, editable=False, blank=True)),
                ('risk_model_fires_size2_percentage', models.FloatField(verbose_name=b'Percentage of size 2 fires.', null=True, editable=False, blank=True)),
                ('population', models.IntegerField(null=True, editable=False, blank=True)),
                ('population_class', models.IntegerField(null=True, editable=False, blank=True)),
                ('featured', models.BooleanField(default=False, editable=False)),
                ('dist_model_score_quartile', models.IntegerField()),
                ('risk_model_deaths_quartile', models.IntegerField()),
                ('risk_model_injuries_quartile', models.IntegerField()),
                ('risk_model_fires_size0_quartile', models.IntegerField()),
                ('risk_model_fires_size1_quartile', models.IntegerField()),
                ('risk_model_fires_size2_quartile', models.IntegerField()),
                ('risk_model_fires_quartile', models.IntegerField()),
                ('risk_model_fires_size1_percentage_risk_model_fires_size2_percen', models.IntegerField()),
                ('risk_model_deaths_risk_model_injuries_quartile', models.IntegerField()),
            ],
            options={
                'abstract': False,
                'db_table': 'population_class_4_quartiles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PopulationClass5Quartile',
            fields=[
                ('id', models.ForeignKey(primary_key=True, db_column=b'id', serialize=False, to='firestation.FireDepartment')),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField(editable=False)),
                ('fdid', models.CharField(max_length=10, editable=False)),
                ('name', models.CharField(max_length=100, editable=False)),
                ('headquarters_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, editable=False, blank=True)),
                ('headquarters_fax', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, editable=False, blank=True)),
                ('department_type', models.CharField(max_length=20, null=True, editable=False, blank=True)),
                ('organization_type', models.CharField(max_length=75, null=True, editable=False, blank=True)),
                ('website', models.URLField(null=True, editable=False, blank=True)),
                ('state', models.CharField(max_length=2, editable=False)),
                ('region', models.CharField(max_length=20, null=True, editable=False, blank=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326, null=True, editable=False, blank=True)),
                ('dist_model_score', models.FloatField(null=True, editable=False, blank=True)),
                ('risk_model_deaths', models.FloatField(verbose_name=b'Predicted deaths per year.', null=True, editable=False, blank=True)),
                ('risk_model_injuries', models.FloatField(verbose_name=b'Predicted injuries per year.', null=True, editable=False, blank=True)),
                ('risk_model_fires', models.FloatField(verbose_name=b'Predicted number of fires per year.', null=True, editable=False, blank=True)),
                ('risk_model_fires_size0', models.FloatField(verbose_name=b'Predicted number of size 0 fires.', null=True, editable=False, blank=True)),
                ('risk_model_fires_size0_percentage', models.FloatField(verbose_name=b'Percentage of size 0 fires.', null=True, editable=False, blank=True)),
                ('risk_model_fires_size1', models.FloatField(verbose_name=b'Predicted number of size 1 fires.', null=True, editable=False, blank=True)),
                ('risk_model_fires_size1_percentage', models.FloatField(verbose_name=b'Percentage of size 1 fires.', null=True, editable=False, blank=True)),
                ('risk_model_fires_size2', models.FloatField(verbose_name=b'Predicted number of size 2 firese.', null=True, editable=False, blank=True)),
                ('risk_model_fires_size2_percentage', models.FloatField(verbose_name=b'Percentage of size 2 fires.', null=True, editable=False, blank=True)),
                ('population', models.IntegerField(null=True, editable=False, blank=True)),
                ('population_class', models.IntegerField(null=True, editable=False, blank=True)),
                ('featured', models.BooleanField(default=False, editable=False)),
                ('dist_model_score_quartile', models.IntegerField()),
                ('risk_model_deaths_quartile', models.IntegerField()),
                ('risk_model_injuries_quartile', models.IntegerField()),
                ('risk_model_fires_size0_quartile', models.IntegerField()),
                ('risk_model_fires_size1_quartile', models.IntegerField()),
                ('risk_model_fires_size2_quartile', models.IntegerField()),
                ('risk_model_fires_quartile', models.IntegerField()),
                ('risk_model_fires_size1_percentage_risk_model_fires_size2_percen', models.IntegerField()),
                ('risk_model_deaths_risk_model_injuries_quartile', models.IntegerField()),
            ],
            options={
                'abstract': False,
                'db_table': 'population_class_5_quartiles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PopulationClass6Quartile',
            fields=[
                ('id', models.ForeignKey(primary_key=True, db_column=b'id', serialize=False, to='firestation.FireDepartment')),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField(editable=False)),
                ('fdid', models.CharField(max_length=10, editable=False)),
                ('name', models.CharField(max_length=100, editable=False)),
                ('headquarters_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, editable=False, blank=True)),
                ('headquarters_fax', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, editable=False, blank=True)),
                ('department_type', models.CharField(max_length=20, null=True, editable=False, blank=True)),
                ('organization_type', models.CharField(max_length=75, null=True, editable=False, blank=True)),
                ('website', models.URLField(null=True, editable=False, blank=True)),
                ('state', models.CharField(max_length=2, editable=False)),
                ('region', models.CharField(max_length=20, null=True, editable=False, blank=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326, null=True, editable=False, blank=True)),
                ('dist_model_score', models.FloatField(null=True, editable=False, blank=True)),
                ('risk_model_deaths', models.FloatField(verbose_name=b'Predicted deaths per year.', null=True, editable=False, blank=True)),
                ('risk_model_injuries', models.FloatField(verbose_name=b'Predicted injuries per year.', null=True, editable=False, blank=True)),
                ('risk_model_fires', models.FloatField(verbose_name=b'Predicted number of fires per year.', null=True, editable=False, blank=True)),
                ('risk_model_fires_size0', models.FloatField(verbose_name=b'Predicted number of size 0 fires.', null=True, editable=False, blank=True)),
                ('risk_model_fires_size0_percentage', models.FloatField(verbose_name=b'Percentage of size 0 fires.', null=True, editable=False, blank=True)),
                ('risk_model_fires_size1', models.FloatField(verbose_name=b'Predicted number of size 1 fires.', null=True, editable=False, blank=True)),
                ('risk_model_fires_size1_percentage', models.FloatField(verbose_name=b'Percentage of size 1 fires.', null=True, editable=False, blank=True)),
                ('risk_model_fires_size2', models.FloatField(verbose_name=b'Predicted number of size 2 firese.', null=True, editable=False, blank=True)),
                ('risk_model_fires_size2_percentage', models.FloatField(verbose_name=b'Percentage of size 2 fires.', null=True, editable=False, blank=True)),
                ('population', models.IntegerField(null=True, editable=False, blank=True)),
                ('population_class', models.IntegerField(null=True, editable=False, blank=True)),
                ('featured', models.BooleanField(default=False, editable=False)),
                ('dist_model_score_quartile', models.IntegerField()),
                ('risk_model_deaths_quartile', models.IntegerField()),
                ('risk_model_injuries_quartile', models.IntegerField()),
                ('risk_model_fires_size0_quartile', models.IntegerField()),
                ('risk_model_fires_size1_quartile', models.IntegerField()),
                ('risk_model_fires_size2_quartile', models.IntegerField()),
                ('risk_model_fires_quartile', models.IntegerField()),
                ('risk_model_fires_size1_percentage_risk_model_fires_size2_percen', models.IntegerField()),
                ('risk_model_deaths_risk_model_injuries_quartile', models.IntegerField()),
            ],
            options={
                'abstract': False,
                'db_table': 'population_class_6_quartiles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PopulationClass7Quartile',
            fields=[
                ('id', models.ForeignKey(primary_key=True, db_column=b'id', serialize=False, to='firestation.FireDepartment')),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField(editable=False)),
                ('fdid', models.CharField(max_length=10, editable=False)),
                ('name', models.CharField(max_length=100, editable=False)),
                ('headquarters_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, editable=False, blank=True)),
                ('headquarters_fax', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, editable=False, blank=True)),
                ('department_type', models.CharField(max_length=20, null=True, editable=False, blank=True)),
                ('organization_type', models.CharField(max_length=75, null=True, editable=False, blank=True)),
                ('website', models.URLField(null=True, editable=False, blank=True)),
                ('state', models.CharField(max_length=2, editable=False)),
                ('region', models.CharField(max_length=20, null=True, editable=False, blank=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326, null=True, editable=False, blank=True)),
                ('dist_model_score', models.FloatField(null=True, editable=False, blank=True)),
                ('risk_model_deaths', models.FloatField(verbose_name=b'Predicted deaths per year.', null=True, editable=False, blank=True)),
                ('risk_model_injuries', models.FloatField(verbose_name=b'Predicted injuries per year.', null=True, editable=False, blank=True)),
                ('risk_model_fires', models.FloatField(verbose_name=b'Predicted number of fires per year.', null=True, editable=False, blank=True)),
                ('risk_model_fires_size0', models.FloatField(verbose_name=b'Predicted number of size 0 fires.', null=True, editable=False, blank=True)),
                ('risk_model_fires_size0_percentage', models.FloatField(verbose_name=b'Percentage of size 0 fires.', null=True, editable=False, blank=True)),
                ('risk_model_fires_size1', models.FloatField(verbose_name=b'Predicted number of size 1 fires.', null=True, editable=False, blank=True)),
                ('risk_model_fires_size1_percentage', models.FloatField(verbose_name=b'Percentage of size 1 fires.', null=True, editable=False, blank=True)),
                ('risk_model_fires_size2', models.FloatField(verbose_name=b'Predicted number of size 2 firese.', null=True, editable=False, blank=True)),
                ('risk_model_fires_size2_percentage', models.FloatField(verbose_name=b'Percentage of size 2 fires.', null=True, editable=False, blank=True)),
                ('population', models.IntegerField(null=True, editable=False, blank=True)),
                ('population_class', models.IntegerField(null=True, editable=False, blank=True)),
                ('featured', models.BooleanField(default=False, editable=False)),
                ('dist_model_score_quartile', models.IntegerField()),
                ('risk_model_deaths_quartile', models.IntegerField()),
                ('risk_model_injuries_quartile', models.IntegerField()),
                ('risk_model_fires_size0_quartile', models.IntegerField()),
                ('risk_model_fires_size1_quartile', models.IntegerField()),
                ('risk_model_fires_size2_quartile', models.IntegerField()),
                ('risk_model_fires_quartile', models.IntegerField()),
                ('risk_model_fires_size1_percentage_risk_model_fires_size2_percen', models.IntegerField()),
                ('risk_model_deaths_risk_model_injuries_quartile', models.IntegerField()),
            ],
            options={
                'abstract': False,
                'db_table': 'population_class_7_quartiles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PopulationClass8Quartile',
            fields=[
                ('id', models.ForeignKey(primary_key=True, db_column=b'id', serialize=False, to='firestation.FireDepartment')),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField(editable=False)),
                ('fdid', models.CharField(max_length=10, editable=False)),
                ('name', models.CharField(max_length=100, editable=False)),
                ('headquarters_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, editable=False, blank=True)),
                ('headquarters_fax', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, editable=False, blank=True)),
                ('department_type', models.CharField(max_length=20, null=True, editable=False, blank=True)),
                ('organization_type', models.CharField(max_length=75, null=True, editable=False, blank=True)),
                ('website', models.URLField(null=True, editable=False, blank=True)),
                ('state', models.CharField(max_length=2, editable=False)),
                ('region', models.CharField(max_length=20, null=True, editable=False, blank=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326, null=True, editable=False, blank=True)),
                ('dist_model_score', models.FloatField(null=True, editable=False, blank=True)),
                ('risk_model_deaths', models.FloatField(verbose_name=b'Predicted deaths per year.', null=True, editable=False, blank=True)),
                ('risk_model_injuries', models.FloatField(verbose_name=b'Predicted injuries per year.', null=True, editable=False, blank=True)),
                ('risk_model_fires', models.FloatField(verbose_name=b'Predicted number of fires per year.', null=True, editable=False, blank=True)),
                ('risk_model_fires_size0', models.FloatField(verbose_name=b'Predicted number of size 0 fires.', null=True, editable=False, blank=True)),
                ('risk_model_fires_size0_percentage', models.FloatField(verbose_name=b'Percentage of size 0 fires.', null=True, editable=False, blank=True)),
                ('risk_model_fires_size1', models.FloatField(verbose_name=b'Predicted number of size 1 fires.', null=True, editable=False, blank=True)),
                ('risk_model_fires_size1_percentage', models.FloatField(verbose_name=b'Percentage of size 1 fires.', null=True, editable=False, blank=True)),
                ('risk_model_fires_size2', models.FloatField(verbose_name=b'Predicted number of size 2 firese.', null=True, editable=False, blank=True)),
                ('risk_model_fires_size2_percentage', models.FloatField(verbose_name=b'Percentage of size 2 fires.', null=True, editable=False, blank=True)),
                ('population', models.IntegerField(null=True, editable=False, blank=True)),
                ('population_class', models.IntegerField(null=True, editable=False, blank=True)),
                ('featured', models.BooleanField(default=False, editable=False)),
                ('dist_model_score_quartile', models.IntegerField()),
                ('risk_model_deaths_quartile', models.IntegerField()),
                ('risk_model_injuries_quartile', models.IntegerField()),
                ('risk_model_fires_size0_quartile', models.IntegerField()),
                ('risk_model_fires_size1_quartile', models.IntegerField()),
                ('risk_model_fires_size2_quartile', models.IntegerField()),
                ('risk_model_fires_quartile', models.IntegerField()),
                ('risk_model_fires_size1_percentage_risk_model_fires_size2_percen', models.IntegerField()),
                ('risk_model_deaths_risk_model_injuries_quartile', models.IntegerField()),
            ],
            options={
                'abstract': False,
                'db_table': 'population_class_8_quartiles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PopulationClass9Quartile',
            fields=[
                ('id', models.ForeignKey(primary_key=True, db_column=b'id', serialize=False, to='firestation.FireDepartment')),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField(editable=False)),
                ('fdid', models.CharField(max_length=10, editable=False)),
                ('name', models.CharField(max_length=100, editable=False)),
                ('headquarters_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, editable=False, blank=True)),
                ('headquarters_fax', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, editable=False, blank=True)),
                ('department_type', models.CharField(max_length=20, null=True, editable=False, blank=True)),
                ('organization_type', models.CharField(max_length=75, null=True, editable=False, blank=True)),
                ('website', models.URLField(null=True, editable=False, blank=True)),
                ('state', models.CharField(max_length=2, editable=False)),
                ('region', models.CharField(max_length=20, null=True, editable=False, blank=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326, null=True, editable=False, blank=True)),
                ('dist_model_score', models.FloatField(null=True, editable=False, blank=True)),
                ('risk_model_deaths', models.FloatField(verbose_name=b'Predicted deaths per year.', null=True, editable=False, blank=True)),
                ('risk_model_injuries', models.FloatField(verbose_name=b'Predicted injuries per year.', null=True, editable=False, blank=True)),
                ('risk_model_fires', models.FloatField(verbose_name=b'Predicted number of fires per year.', null=True, editable=False, blank=True)),
                ('risk_model_fires_size0', models.FloatField(verbose_name=b'Predicted number of size 0 fires.', null=True, editable=False, blank=True)),
                ('risk_model_fires_size0_percentage', models.FloatField(verbose_name=b'Percentage of size 0 fires.', null=True, editable=False, blank=True)),
                ('risk_model_fires_size1', models.FloatField(verbose_name=b'Predicted number of size 1 fires.', null=True, editable=False, blank=True)),
                ('risk_model_fires_size1_percentage', models.FloatField(verbose_name=b'Percentage of size 1 fires.', null=True, editable=False, blank=True)),
                ('risk_model_fires_size2', models.FloatField(verbose_name=b'Predicted number of size 2 firese.', null=True, editable=False, blank=True)),
                ('risk_model_fires_size2_percentage', models.FloatField(verbose_name=b'Percentage of size 2 fires.', null=True, editable=False, blank=True)),
                ('population', models.IntegerField(null=True, editable=False, blank=True)),
                ('population_class', models.IntegerField(null=True, editable=False, blank=True)),
                ('featured', models.BooleanField(default=False, editable=False)),
                ('dist_model_score_quartile', models.IntegerField()),
                ('risk_model_deaths_quartile', models.IntegerField()),
                ('risk_model_injuries_quartile', models.IntegerField()),
                ('risk_model_fires_size0_quartile', models.IntegerField()),
                ('risk_model_fires_size1_quartile', models.IntegerField()),
                ('risk_model_fires_size2_quartile', models.IntegerField()),
                ('risk_model_fires_quartile', models.IntegerField()),
                ('risk_model_fires_size1_percentage_risk_model_fires_size2_percen', models.IntegerField()),
                ('risk_model_deaths_risk_model_injuries_quartile', models.IntegerField()),
            ],
            options={
                'abstract': False,
                'db_table': 'population_class_9_quartiles',
                'managed': False,
            },
        ),
    ]
